theme: jekyll-theme-dinky
title: Papa Koala
description: the french koala

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - about.md
  - homepage.md

